// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmXMQjcmBg8RIa7Mf691oxcdVCKBPpcdw',
    appId: '1:406015064671:web:99d77438c1f2c4393779ea',
    messagingSenderId: '406015064671',
    projectId: 'medquick-c90ac',
    authDomain: 'medquick-c90ac.firebaseapp.com',
    storageBucket: 'medquick-c90ac.appspot.com',
    measurementId: 'G-LEVJ42JK8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfBEJUIm1LWblMPBtFyN2hyLYlOfP4pNQ',
    appId: '1:406015064671:android:15d35ad6b731f8bd3779ea',
    messagingSenderId: '406015064671',
    projectId: 'medquick-c90ac',
    storageBucket: 'medquick-c90ac.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmXMQjcmBg8RIa7Mf691oxcdVCKBPpcdw',
    appId: '1:406015064671:web:2398faf5f07c0ebd3779ea',
    messagingSenderId: '406015064671',
    projectId: 'medquick-c90ac',
    authDomain: 'medquick-c90ac.firebaseapp.com',
    storageBucket: 'medquick-c90ac.appspot.com',
    measurementId: 'G-K1ERXFY2NZ',
  );
}
